baseURL = "https://elijahdanko.net"
title = "Elijah Danko"
theme = "neo-gokarna"
languageCode = "en"
defaultContentLanguage = "en"
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = "G-T1WFJCYQ3B"

# Choose one of emacs, trac or perldoc
pygmentsStyle = "monokai"

[params]
  footer = "Elijah Danko"
  description = "Computer Scientist Enthusiast"
  avatarURL = "/images/main_personal.png"
  avatarSize = "size-m"
  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.13.16/dist/katex.min.css" integrity="sha384-6LkG2wmY8FK9E0vU9OOr8UvLwsaqUg9SETfpq4uTCN1agNe8HRdE9ABlk+fVx6gZ" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.16/dist/katex.min.js" integrity="sha384-31El76TwmbHj4rF9DyLsygbq6xoIobG0W+jqXim+a3dU9W53tdH3A/ngRPxOzzaB" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.13.16/dist/contrib/auto-render.min.js" integrity="sha384-vZTG03m+2yp6N6BNi5iM4rW4oIwk5DfcNdFfxkk9ZWpDriOkXX8voJBFrAO7MpVl" crossorigin="anonymous"
        onload="renderMathInElement(document.body);"></script>
  """
  socialIcons = [
    {name = "linkedin", url = "https://www.linkedin.com/in/elijah-danko-608486bb/"},
    {name = "gmail", url = "mailto:me@elijahdanko.net"},
  ]
  metaKeywords = ["neovim", "emacs", "resume", "open source" ]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Resume"
    url = "/cv/cv.pdf"
    weight = 3

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 4

  [[menu.main]]
    identifier = "github"
    pre = "<span data-feather='github'></span>"
    url = "https://github.com/elijahdanko"
    weight = 5

  # [[menu.main]]
  #   identifier = "rss"
  #   pre = "<span data-feather='rss'></span>"
  #   url = "/index.xml"
  #   weight = 6
